package pane

import (
	"bytes"
	"log"
	"os"
	"sync"

	"github.com/hinshun/vt10x"
)

// VTerm wraps vt10x.Terminal providing thread-safe access.
type VTerm struct {
	mu       sync.Mutex
	term     vt10x.Terminal
	rows     int
	cols     int
	replyBuf bytes.Buffer
	pending  []byte
	inSync   bool
	syncBuf  []byte
	rawBuf   []byte
	rawLog   *log.Logger
}

// NewVTerm creates a new VTerm with the given dimensions.
func NewVTerm(rows, cols int) *VTerm {
	v := &VTerm{rows: rows, cols: cols}
	v.term = vt10x.New(vt10x.WithSize(cols, rows), vt10x.WithWriter(vtReplyWriter{v: v}))
	if os.Getenv("XSSH_VT_DEBUG") == "1" {
		if f, err := os.OpenFile("/tmp/xssh-vt-raw.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0600); err == nil {
			v.rawLog = log.New(f, "vterm: ", log.LstdFlags|log.Lmicroseconds)
		}
	}
	return v
}

// Write feeds raw terminal data into the vt10x parser.
func (v *VTerm) Write(data []byte) {
	v.mu.Lock()
	defer v.mu.Unlock()
	if v.rawLog != nil {
		v.rawLog.Printf("in len=%d bytes=%q", len(data), data)
	}
	v.rawBuf = append(v.rawBuf, data...)

	const syncOn = "\x1b[?2026h"
	const syncOff = "\x1b[?2026l"

	for {
		if !v.inSync {
			start := bytes.Index(v.rawBuf, []byte(syncOn))
			if start < 0 {
				keep := syncPrefixSuffixLen(v.rawBuf, []byte(syncOn))
				cut := len(v.rawBuf) - keep
				if cut > 0 {
					v.writeParsed(v.rawBuf[:cut])
				}
				v.rawBuf = append(v.rawBuf[:0], v.rawBuf[cut:]...)
				return
			}
			if start > 0 {
				v.writeParsed(v.rawBuf[:start])
			}
			v.rawBuf = append(v.rawBuf[:0], v.rawBuf[start+len(syncOn):]...)
			v.inSync = true
			continue
		}

		end := bytes.Index(v.rawBuf, []byte(syncOff))
		if end < 0 {
			keep := syncPrefixSuffixLen(v.rawBuf, []byte(syncOff))
			cut := len(v.rawBuf) - keep
			if cut > 0 {
				v.syncBuf = append(v.syncBuf, v.rawBuf[:cut]...)
			}
			v.rawBuf = append(v.rawBuf[:0], v.rawBuf[cut:]...)
			return
		}

		if end > 0 {
			v.syncBuf = append(v.syncBuf, v.rawBuf[:end]...)
		}
		v.rawBuf = append(v.rawBuf[:0], v.rawBuf[end+len(syncOff):]...)
		v.inSync = false
		v.writeParsed(v.syncBuf)
		v.syncBuf = v.syncBuf[:0]
	}
}

// DrainReplies returns pending terminal responses (e.g. CPR/DSR replies)
// generated by the emulator and clears the buffer.
func (v *VTerm) DrainReplies() []byte {
	v.mu.Lock()
	defer v.mu.Unlock()
	if v.replyBuf.Len() == 0 {
		return nil
	}
	out := append([]byte(nil), v.replyBuf.Bytes()...)
	v.replyBuf.Reset()
	return out
}

// Resize changes the terminal dimensions.
func (v *VTerm) Resize(rows, cols int) {
	v.mu.Lock()
	defer v.mu.Unlock()
	v.rows, v.cols = rows, cols
	v.term.Resize(cols, rows)
}

// Cell returns the glyph at (row, col). Thread-safe.
func (v *VTerm) Cell(row, col int) vt10x.Glyph {
	v.mu.Lock()
	defer v.mu.Unlock()
	return v.term.Cell(col, row)
}

// Cursor returns the current cursor position as (row, col). Thread-safe.
func (v *VTerm) Cursor() (row, col int) {
	v.mu.Lock()
	defer v.mu.Unlock()
	cur := v.term.Cursor()
	return cur.Y, cur.X
}

// CursorVisible reports whether the VT cursor is visible.
func (v *VTerm) CursorVisible() bool {
	v.mu.Lock()
	defer v.mu.Unlock()
	return v.term.CursorVisible()
}

// Size returns (rows, cols).
func (v *VTerm) Size() (rows, cols int) { return v.rows, v.cols }

type vtReplyWriter struct {
	v *VTerm
}

func (w vtReplyWriter) Write(p []byte) (int, error) {
	// Called from vt10x parser while VTerm mutex is held by VTerm.Write.
	if w.v.rawLog != nil {
		w.v.rawLog.Printf("out len=%d bytes=%q", len(p), p)
	}
	return w.v.replyBuf.Write(p)
}

func (v *VTerm) writeParsed(data []byte) {
	if len(data) == 0 {
		return
	}
	in := data
	if len(v.pending) > 0 {
		in = make([]byte, 0, len(v.pending)+len(data))
		in = append(in, v.pending...)
		in = append(in, data...)
	}

	n, err := v.term.Write(in)
	if err != nil {
		return
	}
	if n < len(in) {
		v.pending = append(v.pending[:0], in[n:]...)
		if v.rawLog != nil {
			v.rawLog.Printf("pending len=%d bytes=%q", len(v.pending), v.pending)
		}
		return
	}
	v.pending = v.pending[:0]
}

func syncPrefixSuffixLen(buf, marker []byte) int {
	maxKeep := len(marker) - 1
	if maxKeep > len(buf) {
		maxKeep = len(buf)
	}
	for k := maxKeep; k > 0; k-- {
		if bytes.Equal(buf[len(buf)-k:], marker[:k]) {
			return k
		}
	}
	return 0
}
